apiVersion: argoproj.io/v1aplha1
kind: Application
metadata: 
  name: myapp-argo-app
  namespace: argocd
spec:
  project: default

  source:
    repoURL: git@github.com:georgi-nikolov733/fp-argocd-config.git
    trargetRevision: HEAD
    path: dev
  destination:
    server: https://kubernetes.default.svc
    namespace: myapp

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    # automated: 
    #   selfHeal: true
    #   prune: true
